#!/bin/bash
num_downloads=50
file=http://ipv4.download.thinkbroadband.com/1GB.zip
download_cmd="curl --silent $file --output /dev/null"

if [ -n "$1" ]
then
    num_downloads=$1
fi

for (( i = 0; i < $num_downloads; i++))
do
    echo "$(($i + 1))/$num_downloads"
    $download_cmd &
done

# wait
# echo "Finished"
