#!/bin/bash
# loc='dac'
# loc='23.844,90.401'
options='QF'
widgetInternalName='genmon-15'
# img_path='/tmp/weather.png'

text="$(curl -s "https://wttr.in/$loc?T$options&format=1")" # | ansifilter -M)"
tooltip="$(curl -s https://wttr.in/$loc?$options | ansifilter -M)"
refreshCommand="xfce4-panel --plugin-event=$widgetInternalName:refresh:bool:true"

# curl -s https://wttr.in/$loc_$options.png -o $img_path


echo -n "<txt>$text</txt>"
echo -n "<tool><tt>$tooltip</tt></tool>"
echo -n "<click>$refreshCommand</click><txtclick>$refreshCommand</txtclick>"
